# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be26166d0c9cbb73ee664e223a726cab5bdf4cfd0f77411fa32350c1ce562980c1a97f1aed71f59522e139830b61a2912111f3404cb76183173fd297cf1cc7a7

test:
  secret_key_base: a94eec873879b8a5d5f111d23537b423786ee6cb1080434a12d29f52ab5cdf0820357e8d2a76246e86157186f12d171b8f50db59e378018ce0eca6f282c300c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
